#!/bin/bash

# Configure firewall to redirect port 8080 to 80
sudo sed -i 's/# net\/ipv4\/ip_forward=1/net\/ipv4\/ip_forward=1/' /etc/ufw/sysctl.conf
sudo sed -i 's/# net.ipv4.conf.default.rp_filter=1/net.ipv4.conf.default.rp_filter=0/' /etc/ufw/sysctl.conf
sudo sed -i 's/# net.ipv4.conf.all.rp_filter=1/net.ipv4.conf.all.rp_filter=0/' /etc/ufw/sysctl.conf
sudo sed -i 's/# net\/ipv6\/conf\/default\/forwarding=1/net\/ipv6\/conf\/default\/forwarding=1/' /etc/ufw/sysctl.conf
sudo sed -i 's/# net\/ipv6\/conf\/all\/forwarding=1/net\/ipv6\/conf\/all\/forwarding=1/' /etc/ufw/sysctl.conf

sudo ufw allow 8080/tcp
sudo bash -c "echo '### BEGIN UFW REDIRECT RULES ###' >> /etc/ufw/before.rules"
sudo bash -c "echo '*nat' >> /etc/ufw/before.rules"
sudo bash -c "echo ':PREROUTING ACCEPT [0:0]' >> /etc/ufw/before.rules"
sudo bash -c "echo '-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80' >> /etc/ufw/before.rules"
sudo bash -c "echo 'COMMIT' >> /etc/ufw/before.rules"
sudo bash -c "echo '### END UFW REDIRECT RULES ###' >> /etc/ufw/before.rules"
sudo ufw reload
